insert into location (city, country) values ('Aberaeron', 'England');
insert into location (city, country) values ('Aberdeen ', 'England');
insert into location (city, country) values ('Aberfeldy', 'England');
insert into location (city, country) values ('Abergavenny', 'England');
insert into location (city, country) values ('Abergele', 'England');
insert into location (city, country) values ('Aberystwyth', 'England');
insert into location (city, country) values ('Abingdon ', 'England');
insert into location (city, country) values ('Addlestone', 'England');
insert into location (city, country) values ('Alnwick', 'England');
insert into location (city, country) values ('Alsager', 'England');
insert into location (city, country) values ('Altrincham', 'England');
insert into location (city, country) values ('Ammanford ', 'England');
insert into location (city, country) values ('Andover', 'England');
insert into location (city, country) values ('Anglesey', 'England');
insert into location (city, country) values ('Antrim', 'England');
insert into location (city, country) values ('Arnside', 'England');
insert into location (city, country) values ('Arundel', 'England');
insert into location (city, country) values ('Ashbourne', 'England');
insert into location (city, country) values ('Ashford', 'England');
insert into location (city, country) values ('Axbridge', 'England');
insert into location (city, country) values ('Aylesbury', 'England');
insert into location (city, country) values ('Ayr ', 'England');
insert into location (city, country) values ('Ayrshire', 'England');
insert into location (city, country) values ('BaildonBakewell', 'England');
insert into location (city, country) values ('Balfron ', 'England');
insert into location (city, country) values ('Balloch', 'England');
insert into location (city, country) values ('Banbury', 'England');
insert into location (city, country) values ('Bangor', 'England');
insert into location (city, country) values ('Bangor', 'England');
insert into location (city, country) values ('Barnstaple', 'England');
insert into location (city, country) values ('Barrow-in-furness', 'England');
insert into location (city, country) values ('Basildon & District', 'England');
insert into location (city, country) values ('Basingstoke & Deane', 'England');
insert into location (city, country) values ('Bassetlaw', 'England');
insert into location (city, country) values ('Bath', 'England');
insert into location (city, country) values ('Bath & North East Somerset', 'England');
insert into location (city, country) values ('Bathgate', 'England');
insert into location (city, country) values ('Batley And SpenBeccles', 'England');
insert into location (city, country) values ('Bedford Borough', 'England');
insert into location (city, country) values ('Belfast', 'England');
insert into location (city, country) values ('Berkhamsted', 'England');
insert into location (city, country) values ('Berwick-upon-Tweed', 'England');
insert into location (city, country) values ('BeverleyBewdley', 'England');
insert into location (city, country) values ('Bexhill-on-sea', 'England');
insert into location (city, country) values ('Bicester', 'England');
insert into location (city, country) values ('Biddulph', 'England');
insert into location (city, country) values ('Bideford', 'England');
insert into location (city, country) values ('Billericay', 'England');
insert into location (city, country) values ('BingleyBirmingham', 'England');
insert into location (city, country) values ('Bishopton', 'England');
insert into location (city, country) values ('Blaenau Festiniog', 'England');
insert into location (city, country) values ('Bolton', 'England');
insert into location (city, country) values ('Bourton On Water', 'England');
insert into location (city, country) values ('Bovey Tracey', 'England');
insert into location (city, country) values ('Box', 'England');
insert into location (city, country) values ('Bradford', 'England');
insert into location (city, country) values ('Bradford-on-avon ', 'England');
insert into location (city, country) values ('Braintree & Witham', 'England');
insert into location (city, country) values ('Brampton', 'England');
insert into location (city, country) values ('Brechin', 'England');
insert into location (city, country) values ('Brecon', 'England');
insert into location (city, country) values ('Brentwood', 'England');
insert into location (city, country) values ('Bridgend County', 'England');
insert into location (city, country) values ('Bridgend Town', 'England');
insert into location (city, country) values ('Bridgnorth', 'England');
insert into location (city, country) values ('Brighton And Hove', 'England');
insert into location (city, country) values ('Bristol', 'England');
insert into location (city, country) values ('Broadford', 'England');
insert into location (city, country) values ('Buckingham', 'England');
insert into location (city, country) values ('Burgess Hill', 'England');
insert into location (city, country) values ('Burley In Wharfedale', 'England');
insert into location (city, country) values ('Burnley And Padiham', 'England');
insert into location (city, country) values ('Burntisland', 'England');
insert into location (city, country) values ('Burscough', 'England');
insert into location (city, country) values ('Bury', 'England');
insert into location (city, country) values ('Buxton And Fairfield', 'England');
insert into location (city, country) values ('Caerphilly', 'England');
insert into location (city, country) values ('Caldbeck And Hesket', 'England');
insert into location (city, country) values ('Callington', 'England');
insert into location (city, country) values ('Cam And Dursley', 'England');
insert into location (city, country) values ('Camborne', 'England');
insert into location (city, country) values ('Cambridge ', 'England');
insert into location (city, country) values ('Cambuslang', 'England');
insert into location (city, country) values ('Canterbury ', 'England');
insert into location (city, country) values ('Cardiff ', 'England');
insert into location (city, country) values ('Cardigan', 'England');
insert into location (city, country) values ('Carlisle', 'England');
insert into location (city, country) values ('Carmarthen', 'England');
insert into location (city, country) values ('Carmarthenshire', 'England');
insert into location (city, country) values ('Castle Cary', 'England');
insert into location (city, country) values ('Castle Douglas', 'England');
insert into location (city, country) values ('Ceredigion', 'England');
insert into location (city, country) values ('Charnwood', 'England');
insert into location (city, country) values ('Cheadle', 'England');
insert into location (city, country) values ('Chelmsford', 'England');
insert into location (city, country) values ('Chepstow', 'England');
insert into location (city, country) values ('Cherry Burton Chesham', 'England');
insert into location (city, country) values ('Cheshire West', 'England');
insert into location (city, country) values ('Chester ', 'England');
insert into location (city, country) values ('Chester-le-street ', 'England');
insert into location (city, country) values ('Chesterfield', 'England');
insert into location (city, country) values ('Chew Magna', 'England');
insert into location (city, country) values ('Chichester', 'England');
insert into location (city, country) values ('Chorlton-cum-hardy', 'England');
insert into location (city, country) values ('Church Stretton', 'England');
insert into location (city, country) values ('CirencesterClitheroe', 'England');
insert into location (city, country) values ('Coaley', 'England');
insert into location (city, country) values ('Cockermouth', 'England');
insert into location (city, country) values ('Colchester', 'England');
insert into location (city, country) values ('Colwyn Bay', 'England');
insert into location (city, country) values ('Congleton', 'England');
insert into location (city, country) values ('Coniston And Torver', 'England');
insert into location (city, country) values ('Conwy', 'England');
insert into location (city, country) values ('Conwy Town', 'England');
insert into location (city, country) values ('Coventry', 'England');
insert into location (city, country) values ('Cowbridge', 'England');
insert into location (city, country) values ('Cranleigh', 'England');
insert into location (city, country) values ('Crediton', 'England');
insert into location (city, country) values ('Criccieth', 'England');
insert into location (city, country) values ('Crickhowell', 'England');
insert into location (city, country) values ('Crowborough', 'England');
insert into location (city, country) values ('Cumbria', 'England');
insert into location (city, country) values ('Cupar', 'England');
insert into location (city, country) values ('Curdworth', 'England');
insert into location (city, country) values ('Darley Dale', 'England');
insert into location (city, country) values ('Darlington', 'England');
insert into location (city, country) values ('Datchworth', 'England');
insert into location (city, country) values ('Dawlish', 'England');
insert into location (city, country) values ('Deal', 'England');
insert into location (city, country) values ('Denbigh', 'England');
insert into location (city, country) values ('Denbighshire', 'England');
insert into location (city, country) values ('Derby ', 'England');
insert into location (city, country) values ('Devizes', 'England');
insert into location (city, country) values ('Devon', 'England');
insert into location (city, country) values ('Dinas Powys', 'England');
insert into location (city, country) values ('Doncaster Dorchester', 'England');
insert into location (city, country) values ('Dorking', 'England');
insert into location (city, country) values ('Dornoch', 'England');
insert into location (city, country) values ('Dover', 'England');
insert into location (city, country) values ('Droitwich Spa', 'England');
insert into location (city, country) values ('DronfieldDumfries', 'England');
insert into location (city, country) values ('Dundee ', 'England');
insert into location (city, country) values ('Dundonald', 'England');
insert into location (city, country) values ('Dunoon', 'England');
insert into location (city, country) values ('Dunscore', 'England');
insert into location (city, country) values ('Dunvegan', 'England');
insert into location (city, country) values ('Durham', 'England');
insert into location (city, country) values ('Dyfi Valley', 'England');
insert into location (city, country) values ('East Dunbartonshire', 'England');
insert into location (city, country) values ('East Grinstead', 'England');
insert into location (city, country) values ('East Kilbride', 'England');
insert into location (city, country) values ('East Lothian', 'England');
insert into location (city, country) values ('East Renfrewshire', 'England');
insert into location (city, country) values ('East Staffordshire', 'England');
insert into location (city, country) values ('Easton In Gordano, Pill And Ham Green', 'England');
insert into location (city, country) values ('Eden Valley', 'England');
insert into location (city, country) values ('Edenbridge', 'England');
insert into location (city, country) values ('Edinburgh', 'England');
insert into location (city, country) values ('Egremont', 'England');
insert into location (city, country) values ('Ellon', 'England');
insert into location (city, country) values ('Evesham', 'England');
insert into location (city, country) values ('Exeter', 'England');
insert into location (city, country) values ('Exmouth', 'England');
insert into location (city, country) values ('Fair Isle', 'England');
insert into location (city, country) values ('Fairlie', 'England');
insert into location (city, country) values ('Falkirk', 'England');
insert into location (city, country) values ('Falkirk Zone', 'England');
insert into location (city, country) values ('Falmouth', 'England');
insert into location (city, country) values ('Fareham', 'England');
insert into location (city, country) values ('Faringdon', 'England');
insert into location (city, country) values ('Faversham', 'England');
insert into location (city, country) values ('Felixstowe', 'England');
insert into location (city, country) values ('Fife', 'England');
insert into location (city, country) values ('Flintshire', 'England');
insert into location (city, country) values ('Forest Row', 'England');
insert into location (city, country) values ('Framlingham', 'England');
insert into location (city, country) values ('Frome', 'England');
insert into location (city, country) values ('Fylde', 'England');
insert into location (city, country) values ('Gainsborough', 'England');
insert into location (city, country) values ('Garstang', 'England');
insert into location (city, country) values ('Gateshead', 'England');
insert into location (city, country) values ('Gedling', 'England');
insert into location (city, country) values ('Glasgow', 'England');
insert into location (city, country) values ('Glastonbury', 'England');
insert into location (city, country) values ('Glossopdale', 'England');
insert into location (city, country) values ('Godalming', 'England');
insert into location (city, country) values ('Gosforth & Wasdale', 'England');
insert into location (city, country) values ('Gosport', 'England');
insert into location (city, country) values ('Grange-over-sands', 'England');
insert into location (city, country) values ('Great Ayton', 'England');
insert into location (city, country) values ('Great Torrington', 'England');
insert into location (city, country) values ('Grove', 'England');
insert into location (city, country) values ('Guernsey', 'England');
insert into location (city, country) values ('Guildford', 'England');
insert into location (city, country) values ('GuisboroughGwynedd', 'England');
insert into location (city, country) values ('Hadrians Wall Corridor', 'England');
insert into location (city, country) values ('Hamilton', 'England');
insert into location (city, country) values ('Harlow', 'England');
insert into location (city, country) values ('Harpenden', 'England');
insert into location (city, country) values ('Harrogate', 'England');
insert into location (city, country) values ('Hartlepool', 'England');
insert into location (city, country) values ('Haslemere', 'England');
insert into location (city, country) values ('Havant', 'England');
insert into location (city, country) values ('Haverfordwest', 'England');
insert into location (city, country) values ('HaworthHay-on-wye', 'England');
insert into location (city, country) values ('Hebden Bridge', 'England');
insert into location (city, country) values ('Hemel Hempstead', 'England');
insert into location (city, country) values ('Henley-on-thames', 'England');
insert into location (city, country) values ('Hereford', 'England');
insert into location (city, country) values ('Herefordshire', 'England');
insert into location (city, country) values ('Hertford', 'England');
insert into location (city, country) values ('Hexham', 'England');
insert into location (city, country) values ('Highworth', 'England');
insert into location (city, country) values ('Hinckley & Bosworth', 'England');
insert into location (city, country) values ('Hitchin', 'England');
insert into location (city, country) values ('Holme Valley', 'England');
insert into location (city, country) values ('Holywell', 'England');
insert into location (city, country) values ('Hope Valley', 'England');
insert into location (city, country) values ('Hornsea', 'England');
insert into location (city, country) values ('Horsham', 'England');
insert into location (city, country) values ('Horwich', 'England');
insert into location (city, country) values ('Huddersfield', 'England');
insert into location (city, country) values ('Hull ', 'England');
insert into location (city, country) values ('Huntingdon', 'England');
insert into location (city, country) values ('Huntly', 'England');
insert into location (city, country) values ('Hyndburn', 'England');
insert into location (city, country) values ('IlkleyInverness', 'England');
insert into location (city, country) values ('Inverurie', 'England');
insert into location (city, country) values ('Ipstones And Foxt', 'England');
insert into location (city, country) values ('Ipswich', 'England');
insert into location (city, country) values ('Isle Of Arran', 'England');
insert into location (city, country) values ('Isle Of Iona', 'England');
insert into location (city, country) values ('Isle Of Man', 'England');
insert into location (city, country) values ('Isle Of Wight', 'England');
insert into location (city, country) values ('Ivybridge', 'England');
insert into location (city, country) values ('Jersey', 'England');
insert into location (city, country) values ('Kendal', 'England');
insert into location (city, country) values ('Kenilworth', 'England');
insert into location (city, country) values ('Kennington', 'England');
insert into location (city, country) values ('Keswick', 'England');
insert into location (city, country) values ('Keynsham', 'England');
insert into location (city, country) values ('Kidderminster', 'England');
insert into location (city, country) values ('Kilmalcolm & Quarriers', 'England');
insert into location (city, country) values ('Kinross-shire', 'England');
insert into location (city, country) values ('Kintyre', 'England');
insert into location (city, country) values ('Kirkby Lonsdale', 'England');
insert into location (city, country) values ('Kirkcudbright', 'England');
insert into location (city, country) values ('Kirklees', 'England');
insert into location (city, country) values ('Knighton', 'England');
insert into location (city, country) values ('Knowsley', 'England');
insert into location (city, country) values ('Lakes Parish', 'England');
insert into location (city, country) values ('Lampeter', 'England');
insert into location (city, country) values ('Lancaster ', 'England');
insert into location (city, country) values ('Largs', 'England');
insert into location (city, country) values ('Leatherhead', 'England');
insert into location (city, country) values ('Ledbury', 'England');
insert into location (city, country) values ('LeedsLeek', 'England');
insert into location (city, country) values ('Leicester', 'England');
insert into location (city, country) values ('Leighton Linslade', 'England');
insert into location (city, country) values ('Leiston-cum-sizewell', 'England');
insert into location (city, country) values ('Leominster', 'England');
insert into location (city, country) values ('Letchworth Garden City', 'England');
insert into location (city, country) values ('Lewes', 'England');
insert into location (city, country) values ('Lichfield', 'England');
insert into location (city, country) values ('Lingfield & Dormansland', 'England');
insert into location (city, country) values ('Linlithgow ', 'England');
insert into location (city, country) values ('Liverpool ', 'England');
insert into location (city, country) values ('Livingston', 'England');
insert into location (city, country) values ('Llandrindod Wells', 'England');
insert into location (city, country) values ('Llandudno', 'England');
insert into location (city, country) values ('Llangefni', 'England');
insert into location (city, country) values ('Llangollen', 'England');
insert into location (city, country) values ('Llanidloes', 'England');
insert into location (city, country) values ('Llantwit Major', 'England');
insert into location (city, country) values ('Llanwrst', 'England');
insert into location (city, country) values ('Lochgelly', 'England');
insert into location (city, country) values ('Lochwinnoch', 'England');
insert into location (city, country) values ('London', 'England');
insert into location (city, country) values ('London, Brent', 'England');
insert into location (city, country) values ('London, Camden', 'England');
insert into location (city, country) values ('London, City Of London', 'England');
insert into location (city, country) values ('London, Croydon', 'England');
insert into location (city, country) values ('London, Ealing', 'England');
insert into location (city, country) values ('London, Enfield', 'England');
insert into location (city, country) values ('London, Greenwich', 'England');
insert into location (city, country) values ('London, Hackney', 'England');
insert into location (city, country) values ('London, Hammersmith & Fulham', 'England');
insert into location (city, country) values ('London, Haringey', 'England');
insert into location (city, country) values ('London, Hounslow', 'England');
insert into location (city, country) values ('London, Islington', 'England');
insert into location (city, country) values ('London, Kingston', 'England');
insert into location (city, country) values ('London, Lambeth', 'England');
insert into location (city, country) values ('London, Lewisham', 'England');
insert into location (city, country) values ('London, Newham', 'England');
insert into location (city, country) values ('London, Redbridge', 'England');
insert into location (city, country) values ('London, Richmond', 'England');
insert into location (city, country) values ('London, Southwark', 'England');
insert into location (city, country) values ('London, Sutton', 'England');
insert into location (city, country) values ('London, Tower Hamlets', 'England');
insert into location (city, country) values ('London, Waltham Forest', 'England');
insert into location (city, country) values ('Longniddry', 'England');
insert into location (city, country) values ('Louth', 'England');
insert into location (city, country) values ('Lowestoft', 'England');
insert into location (city, country) values ('Ludlow', 'England');
insert into location (city, country) values ('Luton', 'England');
insert into location (city, country) values ('Lutterworth', 'England');
insert into location (city, country) values ('Macclesfield', 'England');
insert into location (city, country) values ('Maidstone', 'England');
insert into location (city, country) values ('Malmesbury', 'England');
insert into location (city, country) values ('Malton And NortonMalvern', 'England');
insert into location (city, country) values ('Manchester', 'England');
insert into location (city, country) values ('Market Harborough', 'England');
insert into location (city, country) values ('Matlock & District', 'England');
insert into location (city, country) values ('Medway', 'England');
insert into location (city, country) values ('Melksham', 'England');
insert into location (city, country) values ('Melton Mowbray', 'England');
insert into location (city, country) values ('Menai Bridge', 'England');
insert into location (city, country) values ('Merthyr Tydfil ', 'England');
insert into location (city, country) values ('Merthyr Tydfil County', 'England');
insert into location (city, country) values ('Merton', 'England');
insert into location (city, country) values ('Mid-formartine', 'England');
insert into location (city, country) values ('MiddlesbroughMidsomer Norton ', 'England');
insert into location (city, country) values ('Milford Haven', 'England');
insert into location (city, country) values ('Millom ', 'England');
insert into location (city, country) values ('Milton Keynes', 'England');
insert into location (city, country) values ('Minehead', 'England');
insert into location (city, country) values ('Mirfield', 'England');
insert into location (city, country) values ('Mold', 'England');
insert into location (city, country) values ('Monmouth', 'England');
insert into location (city, country) values ('Monmouthshire', 'England');
insert into location (city, country) values ('Montrose', 'England');
insert into location (city, country) values ('Morpeth', 'England');
insert into location (city, country) values ('Mossley', 'England');
insert into location (city, country) values ('Motherwell', 'England');
insert into location (city, country) values ('Musselburgh', 'England');
insert into location (city, country) values ('Nailsworth', 'England');
insert into location (city, country) values ('Neath', 'England');
insert into location (city, country) values ('Neath Port Talbot', 'England');
insert into location (city, country) values ('New Mills', 'England');
insert into location (city, country) values ('Newbury', 'England');
insert into location (city, country) values ('Newcastle-under-Lyme', 'England');
insert into location (city, country) values ('Newcastle-upon-Tyne', 'England');
insert into location (city, country) values ('Newnham On Severn', 'England');
insert into location (city, country) values ('Newport', 'England');
insert into location (city, country) values ('Newton Abbot', 'England');
insert into location (city, country) values ('North Berwick', 'England');
insert into location (city, country) values ('North Tyneside', 'England');
insert into location (city, country) values ('Northallerton', 'England');
insert into location (city, country) values ('Northampton', 'England');
insert into location (city, country) values ('Norwich', 'England');
insert into location (city, country) values ('Nottingham', 'England');
insert into location (city, country) values ('Oadby', 'England');
insert into location (city, country) values ('Oban & District', 'England');
insert into location (city, country) values ('Okehampton', 'England');
insert into location (city, country) values ('Oldham', 'England');
insert into location (city, country) values ('Oswestry', 'England');
insert into location (city, country) values ('OtleyOundle', 'England');
insert into location (city, country) values ('Oxford', 'England');
insert into location (city, country) values ('Painswick', 'England');
insert into location (city, country) values ('Paisley', 'England');
insert into location (city, country) values ('Papa Westray', 'England');
insert into location (city, country) values ('Peebles & Tweeddale', 'England');
insert into location (city, country) values ('Penarth', 'England');
insert into location (city, country) values ('Pendle', 'England');
insert into location (city, country) values ('PenistonePershore', 'England');
insert into location (city, country) values ('Perth', 'England');
insert into location (city, country) values ('Petersfield', 'England');
insert into location (city, country) values ('PickeringPlymouth', 'England');
insert into location (city, country) values ('PocklingtonPonteland', 'England');
insert into location (city, country) values ('Porthcawl', 'England');
insert into location (city, country) values ('Portsmouth', 'England');
insert into location (city, country) values ('Port Talbot', 'England');
insert into location (city, country) values ('Powys', 'England');
insert into location (city, country) values ('Prestatyn & Meliden', 'England');
insert into location (city, country) values ('Preston', 'England');
insert into location (city, country) values ('Prestonpans', 'England');
insert into location (city, country) values ('Pulborough', 'England');
insert into location (city, country) values ('Purbeck', 'England');
insert into location (city, country) values ('Queensferry', 'England');
insert into location (city, country) values ('Reading ', 'England');
insert into location (city, country) values ('Renfrewshire', 'England');
insert into location (city, country) values ('Rhondda Cynon Taff', 'England');
insert into location (city, country) values ('Rhyl', 'England');
insert into location (city, country) values ('Richmond, Yorkshire', 'England');
insert into location (city, country) values ('Ringwood', 'England');
insert into location (city, country) values ('Ripon', 'England');
insert into location (city, country) values ('Rochdale', 'England');
insert into location (city, country) values ('Romsey', 'England');
insert into location (city, country) values ('Ross On Wye', 'England');
insert into location (city, country) values ('RotherhamRoyal Leamington Spa', 'England');
insert into location (city, country) values ('Rushmoor', 'England');
insert into location (city, country) values ('Rutherglen', 'England');
insert into location (city, country) values ('Rutland', 'England');
insert into location (city, country) values ('Rye', 'England');
insert into location (city, country) values ('Salford', 'England');
insert into location (city, country) values ('Salisbury', 'England');
insert into location (city, country) values ('Sandbach', 'England');
insert into location (city, country) values ('Sawtry', 'England');
insert into location (city, country) values ('ScarboroughSeaford', 'England');
insert into location (city, country) values ('Sefton', 'England');
insert into location (city, country) values ('Selkirk', 'England');
insert into location (city, country) values ('Sevenoaks', 'England');
insert into location (city, country) values ('Shaftesbury', 'England');
insert into location (city, country) values ('SheffieldShetland Islands', 'England');
insert into location (city, country) values ('ShipleyShrewsbury', 'England');
insert into location (city, country) values ('Shrivenham & Watchfield', 'England');
insert into location (city, country) values ('Shropshire', 'England');
insert into location (city, country) values ('Sleaford', 'England');
insert into location (city, country) values ('Slough', 'England');
insert into location (city, country) values ('Solihull', 'England');
insert into location (city, country) values ('Somerset', 'England');
insert into location (city, country) values ('South Gloucestershire', 'England');
insert into location (city, country) values ('South Holland', 'England');
insert into location (city, country) values ('South Ribble', 'England');
insert into location (city, country) values ('Southampton', 'England');
insert into location (city, country) values ('Southend-on-sea', 'England');
insert into location (city, country) values ('Southwell', 'England');
insert into location (city, country) values ('St Albans', 'England');
insert into location (city, country) values ('St Andrews', 'England');
insert into location (city, country) values ('St Austell', 'England');
insert into location (city, country) values ('St Davids', 'England');
insert into location (city, country) values ('St Helens', 'England');
insert into location (city, country) values ('St Ives', 'England');
insert into location (city, country) values ('St Neots', 'England');
insert into location (city, country) values ('Stafford', 'England');
insert into location (city, country) values ('Stafford Borough', 'England');
insert into location (city, country) values ('Staffordshire County', 'England');
insert into location (city, country) values ('Stamford', 'England');
insert into location (city, country) values ('Stevenage ', 'England');
insert into location (city, country) values ('Stirling', 'England');
insert into location (city, country) values ('Stockbridge', 'England');
insert into location (city, country) values ('Stockport', 'England');
insert into location (city, country) values ('Stockton-on-tees', 'England');
insert into location (city, country) values ('Stoke-on-trent', 'England');
insert into location (city, country) values ('StokesleyStourbridge', 'England');
insert into location (city, country) values ('Stourport-on-severn', 'England');
insert into location (city, country) values ('Stratford-upon-avon', 'England');
insert into location (city, country) values ('Strathaven', 'England');
insert into location (city, country) values ('Strathblane & Blanefield', 'England');
insert into location (city, country) values ('Stroud', 'England');
insert into location (city, country) values ('Sunderland', 'England');
insert into location (city, country) values ('Swanage', 'England');
insert into location (city, country) values ('Swansea City', 'England');
insert into location (city, country) values ('Swindon', 'England');
insert into location (city, country) values ('TadcasterTatsfield', 'England');
insert into location (city, country) values ('Taunton', 'England');
insert into location (city, country) values ('Tavistock', 'England');
insert into location (city, country) values ('Teignmouth', 'England');
insert into location (city, country) values ('Test Valley', 'England');
insert into location (city, country) values ('Tewkesbury', 'England');
insert into location (city, country) values ('Thanet', 'England');
insert into location (city, country) values ('Thatcham', 'England');
insert into location (city, country) values ('Thornbury', 'England');
insert into location (city, country) values ('Thornton', 'England');
insert into location (city, country) values ('Three Rivers', 'England');
insert into location (city, country) values ('Tiverton', 'England');
insert into location (city, country) values ('Todmorden', 'England');
insert into location (city, country) values ('Torbay', 'England');
insert into location (city, country) values ('Totnes', 'England');
insert into location (city, country) values ('Trafford', 'England');
insert into location (city, country) values ('Tring ', 'England');
insert into location (city, country) values ('Troon', 'England');
insert into location (city, country) values ('Trowbridge', 'England');
insert into location (city, country) values ('Truro', 'England');
insert into location (city, country) values ('Tunbridge Wells', 'England');
insert into location (city, country) values ('Uckfield', 'England');
insert into location (city, country) values ('Ullapool', 'England');
insert into location (city, country) values ('Ulverston', 'England');
insert into location (city, country) values ('Uphall', 'England');
insert into location (city, country) values ('Usk', 'England');
insert into location (city, country) values ('Vale Of Glamorgan', 'England');
insert into location (city, country) values ('Vale Royal Borough', 'England');
insert into location (city, country) values ('Ware', 'England');
insert into location (city, country) values ('Wareham', 'England');
insert into location (city, country) values ('Warminster', 'England');
insert into location (city, country) values ('Warrington', 'England');
insert into location (city, country) values ('Watford', 'England');
insert into location (city, country) values ('Wellingborough', 'England');
insert into location (city, country) values ('Wells', 'England');
insert into location (city, country) values ('Wells-next-the-sea', 'England');
insert into location (city, country) values ('Welwyn Hatfield', 'England');
insert into location (city, country) values ('West Lothian', 'England');
insert into location (city, country) values ('Westray', 'England');
insert into location (city, country) values ('Weymouth & Portland', 'England');
insert into location (city, country) values ('Whitburn', 'England');
insert into location (city, country) values ('Whitchurch', 'England');
insert into location (city, country) values ('Wigan', 'England');
insert into location (city, country) values ('Wigton', 'England');
insert into location (city, country) values ('Wigtown', 'England');
insert into location (city, country) values ('Wimborne Minster', 'England');
insert into location (city, country) values ('Winchcombe And Greet', 'England');
insert into location (city, country) values ('Winchester', 'England');
insert into location (city, country) values ('Windermere & Bowness', 'England');
insert into location (city, country) values ('Windsor & Maidenhead', 'England');
insert into location (city, country) values ('Winscombe And Sandford', 'England');
insert into location (city, country) values ('Wirksworth', 'England');
insert into location (city, country) values ('Wirral', 'England');
insert into location (city, country) values ('Witney', 'England');
insert into location (city, country) values ('Wiveliscombe', 'England');
insert into location (city, country) values ('Wivenhoe', 'England');
insert into location (city, country) values ('Woking', 'England');
insert into location (city, country) values ('Wolverhampton', 'England');
insert into location (city, country) values ('Woodbridge', 'England');
insert into location (city, country) values ('Woodhall Spa', 'England');
insert into location (city, country) values ('Worcester', 'England');
insert into location (city, country) values ('Worthing', 'England');
insert into location (city, country) values ('Wotton Under Edge', 'England');
insert into location (city, country) values ('Wrexham Town', 'England');
insert into location (city, country) values ('Wrexham Zone', 'England');
insert into location (city, country) values ('Wymondham', 'England');
insert into location (city, country) values ('Yate', 'England');
insert into location (city, country) values ('Yatton & Claverham', 'England');
insert into location (city, country) values ('York', 'England');
